/** The word bank: every animal and trait a level may use, with what its sticker looks like. */

export interface AnimalInfo {
  emoji: string;
}

/** Where the trait's accessory sits on the sticker. */
export type Spot = 'head' | 'corner' | 'face' | 'side';

export interface TraitInfo {
  emoji: string;
  spot: Spot;
  /** Optional pose for the animal (CSS class `fx-<name>`). */
  fx?: string;
}

export const ANIMALS: Record<string, AnimalInfo> = {
  ANT: { emoji: '🐜' },
  BADGER: { emoji: '🦡' },
  BAT: { emoji: '🦇' },
  BEAR: { emoji: '🐻' },
  BEAVER: { emoji: '🦫' },
  BEE: { emoji: '🐝' },
  BEETLE: { emoji: '🪲' },
  BISON: { emoji: '🦬' },
  BUNNY: { emoji: '🐰' },
  CAMEL: { emoji: '🐪' },
  CAT: { emoji: '🐱' },
  CHICK: { emoji: '🐤' },
  COW: { emoji: '🐮' },
  CRAB: { emoji: '🦀' },
  CRICKET: { emoji: '🦗' },
  DEER: { emoji: '🦌' },
  DOG: { emoji: '🐶' },
  DONKEY: { emoji: '🫏' },
  DOVE: { emoji: '🕊️' },
  DUCK: { emoji: '🦆' },
  EAGLE: { emoji: '🦅' },
  FISH: { emoji: '🐟' },
  FLAMINGO: { emoji: '🦩' },
  FOX: { emoji: '🦊' },
  FROG: { emoji: '🐸' },
  GIRAFFE: { emoji: '🦒' },
  GOAT: { emoji: '🐐' },
  GOOSE: { emoji: '🪿' },
  GORILLA: { emoji: '🦍' },
  HEDGEHOG: { emoji: '🦔' },
  HEN: { emoji: '🐔' },
  HIPPO: { emoji: '🦛' },
  HORSE: { emoji: '🐴' },
  KOALA: { emoji: '🐨' },
  LADYBUG: { emoji: '🐞' },
  LEOPARD: { emoji: '🐆' },
  LION: { emoji: '🦁' },
  LLAMA: { emoji: '🦙' },
  LOBSTER: { emoji: '🦞' },
  MONKEY: { emoji: '🐵' },
  MOOSE: { emoji: '🫎' },
  MOUSE: { emoji: '🐭' },
  OTTER: { emoji: '🦦' },
  OWL: { emoji: '🦉' },
  OX: { emoji: '🐂' },
  OYSTER: { emoji: '🦪' },
  PANDA: { emoji: '🐼' },
  PEACOCK: { emoji: '🦚' },
  PENGUIN: { emoji: '🐧' },
  PIG: { emoji: '🐷' },
  RACCOON: { emoji: '🦝' },
  RAT: { emoji: '🐀' },
  RHINO: { emoji: '🦏' },
  ROOSTER: { emoji: '🐓' },
  SCORPION: { emoji: '🦂' },
  SEAL: { emoji: '🦭' },
  SHARK: { emoji: '🦈' },
  SHEEP: { emoji: '🐑' },
  SHRIMP: { emoji: '🦐' },
  SLOTH: { emoji: '🦥' },
  SNAIL: { emoji: '🐌' },
  SNAKE: { emoji: '🐍' },
  SPIDER: { emoji: '🕷️' },
  SQUID: { emoji: '🦑' },
  SWAN: { emoji: '🦢' },
  TIGER: { emoji: '🐯' },
  TURKEY: { emoji: '🦃' },
  TURTLE: { emoji: '🐢' },
  UNICORN: { emoji: '🦄' },
  WHALE: { emoji: '🐳' },
  WOLF: { emoji: '🐺' },
  WORM: { emoji: '🪱' },
};

export const TRAITS: Record<string, TraitInfo> = {
  ANGRY: { emoji: '💢', spot: 'corner', fx: 'angry' },
  BOLD: { emoji: '⚡', spot: 'corner' },
  BRAVE: { emoji: '🛡️', spot: 'side' },
  BUSY: { emoji: '📋', spot: 'side' },
  CALM: { emoji: '🍵', spot: 'side' },
  CHEEKY: { emoji: '😜', spot: 'corner', fx: 'silly' },
  CHILLY: { emoji: '❄️', spot: 'corner', fx: 'chilly' },
  CHUBBY: { emoji: '🍰', spot: 'side' },
  CLEVER: { emoji: '💡', spot: 'head' },
  CLUMSY: { emoji: '🩹', spot: 'head', fx: 'silly' },
  COOL: { emoji: '🕶️', spot: 'face' },
  CRAZY: { emoji: '🌀', spot: 'head', fx: 'dizzy' },
  CURIOUS: { emoji: '❓', spot: 'corner', fx: 'curious' },
  CUTE: { emoji: '💕', spot: 'corner' },
  DIZZY: { emoji: '💫', spot: 'head', fx: 'dizzy' },
  EAGER: { emoji: '⭐', spot: 'corner', fx: 'curious' },
  FANCY: { emoji: '🎩', spot: 'head' },
  FIERCE: { emoji: '🔥', spot: 'corner', fx: 'angry' },
  FUNNY: { emoji: '😂', spot: 'corner', fx: 'silly' },
  GENTLE: { emoji: '🌷', spot: 'side' },
  GREEDY: { emoji: '💰', spot: 'side' },
  GRUMPY: { emoji: '🌧️', spot: 'head' },
  HAPPY: { emoji: '🌈', spot: 'corner' },
  HASTY: { emoji: '⏰', spot: 'side', fx: 'speedy' },
  HUNGRY: { emoji: '🍩', spot: 'side' },
  JOLLY: { emoji: '🎉', spot: 'corner' },
  LAZY: { emoji: '💤', spot: 'corner', fx: 'lazy' },
  LONELY: { emoji: '🍂', spot: 'corner', fx: 'shy' },
  LOUD: { emoji: '📢', spot: 'side' },
  LUCKY: { emoji: '🍀', spot: 'corner' },
  MAGICAL: { emoji: '✨', spot: 'corner', fx: 'magical' },
  MERRY: { emoji: '🎄', spot: 'side' },
  MESSY: { emoji: '🎨', spot: 'side', fx: 'silly' },
  MIGHTY: { emoji: '💪', spot: 'side' },
  NOISY: { emoji: '🥁', spot: 'side' },
  NOSY: { emoji: '👀', spot: 'corner', fx: 'curious' },
  PICKY: { emoji: '🍴', spot: 'side' },
  PLUMP: { emoji: '🍑', spot: 'side' },
  POLITE: { emoji: '🎀', spot: 'head' },
  PROUD: { emoji: '🏅', spot: 'side' },
  QUICK: { emoji: '⏱️', spot: 'side', fx: 'speedy' },
  ROYAL: { emoji: '👑', spot: 'head' },
  SALTY: { emoji: '🧂', spot: 'side' },
  SASSY: { emoji: '💅', spot: 'side' },
  SHY: { emoji: '🌸', spot: 'corner', fx: 'shy' },
  SILLY: { emoji: '🎈', spot: 'side', fx: 'silly' },
  SLEEPY: { emoji: '🌙', spot: 'corner', fx: 'sleepy' },
  SLY: { emoji: '🎭', spot: 'corner', fx: 'shy' },
  SNEAKY: { emoji: '🥷', spot: 'corner', fx: 'sneaky' },
  SOGGY: { emoji: '☔', spot: 'head', fx: 'chilly' },
  SPEEDY: { emoji: '💨', spot: 'side', fx: 'speedy' },
  SPOOKY: { emoji: '👻', spot: 'corner', fx: 'spooky' },
  STRONG: { emoji: '🥊', spot: 'side' },
  SWEET: { emoji: '🍭', spot: 'side' },
  TIDY: { emoji: '🧹', spot: 'side' },
  TINY: { emoji: '🔍', spot: 'corner', fx: 'tiny' },
  WILD: { emoji: '🌿', spot: 'head' },
  WISE: { emoji: '🎓', spot: 'head' },
};

const title = (word: string) => word.charAt(0) + word.slice(1).toLowerCase();

export const stickerName = (adjective: string, animal: string): string => `${title(adjective)} ${title(animal)}`;
